---
- name: Download wordpress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no
  sudo: yes

- name: Extracao do wordpress para diretorio do apache
  unarchive:
     src=/tmp/wordpress.tar.gz 
     dest=/var/www/
     copy=no
  sudo: yes

- name: Atualizar documento raiz para o wordpress
  sudo: yes
  lineinfile:
     dest=/etc/apache2/sites-enabled/000-default.conf regexp="(.)+DocumentRoot /var/www/html" line="DocumentRoot /var/www/wordpress"
  notify:
    - Reiniciando o Apache

- name: Configurações do Wordpress
  command: 
    mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  sudo: yes

- name: Atualizar arquivo de configuracao do wordpress
  sudo: yes
  lineinfile:
    dest=/var/www/wordpress/wp-config.php regexp="{{ item.regexp }}" line="{{ item.line }}"
    
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ wp_mysql_db }}');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ wp_mysql_user }}');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ wp_mysql_password }}');"}


# tasks file for wordpress
